#!/usr/bin/env bash
# configures an Ubuntu server with the Requirements: localhost resolves to 127.0.0.2 , facebook.com resolves to 8.8.8.8.

sudo cp "/etc/hosts" "/tmp/hosts.tmp"
sudo cp "/etc/hosts" "/etc/hosts.bak"

sudo sed -i "s/^127.0.0.1\s\+localhost/127.0.0.2 localhost/" /tmp/hosts.tmp

if grep -q "facebook.com" "/tmp/hosts.tmp"; then
    sudo sed -i "s/.*facebook.com/8.8.8.8 facebook.com/" /tmp/hosts.tmp

else
    echo "8.8.8.8 facebook.com" | sudo tee -a /tmp/hosts.tmp
fi

sudo cp /tmp/hosts.tmp /etc/hosts
sudo rm /tmp/hosts.tmp
